// Code generated by MockGen. DO NOT EDIT.
// Source: user.pb.go

// Package mock_proto is a generated GoMock package.
package mock_proto

import (
	context "context"
	reflect "reflect"

	proto "github.com/crafted-systems/smartcollect-pro/user/proto"
	gomock "github.com/golang/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockUserClient is a mock of UserClient interface.
type MockUserClient struct {
	ctrl     *gomock.Controller
	recorder *MockUserClientMockRecorder
}

// MockUserClientMockRecorder is the mock recorder for MockUserClient.
type MockUserClientMockRecorder struct {
	mock *MockUserClient
}

// NewMockUserClient creates a new mock instance.
func NewMockUserClient(ctrl *gomock.Controller) *MockUserClient {
	mock := &MockUserClient{ctrl: ctrl}
	mock.recorder = &MockUserClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserClient) EXPECT() *MockUserClientMockRecorder {
	return m.recorder
}

// AMethod mocks base method.
func (m *MockUserClient) AMethod(ctx context.Context, in *proto.OK, opts ...grpc.CallOption) (*proto.OK, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AMethod", varargs...)
	ret0, _ := ret[0].(*proto.OK)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AMethod indicates an expected call of AMethod.
func (mr *MockUserClientMockRecorder) AMethod(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AMethod", reflect.TypeOf((*MockUserClient)(nil).AMethod), varargs...)
}

// MockUserServer is a mock of UserServer interface.
type MockUserServer struct {
	ctrl     *gomock.Controller
	recorder *MockUserServerMockRecorder
}

// MockUserServerMockRecorder is the mock recorder for MockUserServer.
type MockUserServerMockRecorder struct {
	mock *MockUserServer
}

// NewMockUserServer creates a new mock instance.
func NewMockUserServer(ctrl *gomock.Controller) *MockUserServer {
	mock := &MockUserServer{ctrl: ctrl}
	mock.recorder = &MockUserServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserServer) EXPECT() *MockUserServerMockRecorder {
	return m.recorder
}

// AMethod mocks base method.
func (m *MockUserServer) AMethod(arg0 context.Context, arg1 *proto.OK) (*proto.OK, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AMethod", arg0, arg1)
	ret0, _ := ret[0].(*proto.OK)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AMethod indicates an expected call of AMethod.
func (mr *MockUserServerMockRecorder) AMethod(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AMethod", reflect.TypeOf((*MockUserServer)(nil).AMethod), arg0, arg1)
}
